# Nome do workflow, aparece na "Actions"
name: Pipeline CI/CD  
# Definir quando o nosso PIPELINE será disparado
on:
  push:
   branches:
   - main
  workflow_dispatch: # habilitar o botão "Run workflow" no GitHub Actions
 
jobs:
 #Primeiro job: build
  build:
    runs-on: ubuntu-latest # Imagem da máquina usada no CI
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalação das dependências    
        run: npm install 
        
      - name: Rodar o build
        run: npm run build
